### PR TITLE
Improve error handling when creating hosts

### LINKED ISSUE #18: Hostname validation doesn't work for non-admin user
For the non-admin user the hosts query only returns records that the user is authorised, so it happens that a name that is already taken is displayed as available

### PR DESCRIPTION
**Pull request by kamils-iRonin**
Fixes #18 

image

### CODE REVIEW

**Comment by timogoebel** [comment]
I guess we basically need both:
- The proper error message is great to have!
- But we should try to prevent the error in the first place. I guess we don't have a suitable API endpoint to figure out if a name has already been taken. How much effort would it be to add something like that?

**Comment by kamils-iRonin** [comment]
> But we should try to prevent the error in the first place. I guess we don't have a suitable API endpoint to figure out if a name has already been taken. How much effort would it be to add something like that?

Hi @timogoebel  👋 

We could use `POST /api/v2/hosts/` with payload: 

```json
{
  "name": "test.example.com"
}
```

This, obviously, won't create the host but we can check if there are any errors in the name (as in the example below). 

```json
{
    "error":
    {
        "errors":
        {
            "architecture_id":
            [
                "can't be blank"
            ],
            "interfaces.mac":
            [
                "can't be blank"
            ],
            "location_id":
            [
                "can't be blank"
            ],
            "name":
            [
                "has already been taken"
            ],
            "operatingsystem_id":
            [
                "can't be blank"
            ]
        },
        "full_messages":
        [
            "Mac can't be blank",
            "Name has already been taken",
            "Operatingsystem can't be blank",
            "Location can't be blank",
            "Architecture can't be blank"
        ],
        "id": null
    }
}
```

This way we don't need any API changes. We can introduce a new endpoint but it won't be available in old Foreman versions.

**Comment by laugmanuel** [comment]
> > But we should try to prevent the error in the first place. I guess we don't have a suitable API endpoint to figure out if a name has already been taken. How much effort would it be to add something like that?
> 
> Hi @timogoebel 👋
> 
> We could use `POST /api/v2/hosts/` with payload:
> 
> ```json
> {
>   "name": "test.example.com"
> }
> ```

This sounds like an ok solution for me. We just need to keep in mind that every API call of this kind causes errors in Foreman log, which do pollute the log.

So a new host will always at least create one error for the name check (where all required parameters are missing) and one successful request containing all the data.

Should we hide this behind a feature flag/setting?

**Comment by timogoebel** [comment]
> Should we hide this behind a feature flag/setting?

You are right. The errors in the log aren't really pretty. Well, maybe we should split this up:
- How about we leave the check for known hosts and add the proper error handling in this PR.
- We file a PR to foreman core to add a proper endpoint (I guess we would want to query if a name is still available. it might be a good idea to check for the name suggestion service there is in core if this is related or not).
- We improve the feature in lisa.

WDYT?

**Comment by danielwieberneit** [comment]
i think we should focus on the proper error handling. Changing foreman core sounds to be a lot of work for something that is little used.

**Comment by kamils-iRonin** [comment]
I've updated this, it's just about proper errors handling now

**Review by laugmanuel — APPROVED** [review]
LGTM!

**Comment by laugmanuel** [comment]
Thanks @kamils-iRonin !

**Pull request merged**
