### PR TITLE
Set correct computeResourceId when the location is changed

### LINKED ISSUE #21: `computeResourceId` does not get set correctly in the final host creation call
`computeResourceId` gets initialised to the compute resource for the default location in settings/index.js, however it never gets changed when the location is changed, even though the `computeResource` itself is.
This results in foreman trying to create a host on a computeResource that might not be available in the alternate location.

My current solution is to simply add
```
  set(data, 'computeResourceId', computeResource.id)
```
to `hostCreatParams.js`, but as I'm not that great with JavaScript this looks like a big hack.

### PR DESCRIPTION
**Pull request by kamils-iRonin**
fix #21

### CODE REVIEW

**Comment by kamils-iRonin** [comment]
@SimonPe could you please check if this fixes the issue for you?

**Comment by SimonPe** [comment]
Looks like it would, but I'm shutting down for today so it'll probably have to wait till tomorrow before I can test it.
Big thanks for looking this quickly into it.

**Comment by timogoebel** [comment]
@laugmanuel: This looks good to me. Can we merge?

**Comment by laugmanuel** [comment]
@timogoebel, yes I'm fine with that. Did the fix work for you @SimonPe?

**Pull request merged**
